import("GameDatabase")
GameDatabase:set(ggd.Debug__StartMission, "action_review_e")
GameDatabase:set(ggd.Debug__ForceLevelMax, true)
GameDatabase:set(ggd.Debug__DisableGameOver, true)
dofile("/Game/LaunchScript/root.lua")
