import("GameDatabase")
GameDatabase:set(ggd.Debug__StartMission, "ft98")
GameDatabase:set(ggd.Debug__ForceLevelMax, true)
GameDatabase:set(ggd.Debug__DisableGameOver, true)
dofile("/Game/LaunchScript/root.lua")
