import("GameDatabase")
GameDatabase:set(ggd__Debug__StartMission, "sm90_a")
GameDatabase:set(ggd__Debug__ForceLevelMax, true)
dofile("/Game/LaunchScript/root.lua")
GameDatabase:set(ggd__Savedata__EventManageFlags__CurrentFreeMode, "ft90")
