L0_0 = import
L0_0("math")
L0_0 = import
L0_0("Debug")
L0_0 = import
L0_0("HUD")
L0_0 = import
L0_0("Font")
L0_0 = import
L0_0("Pad")
L0_0 = dofile
L0_0("/Debug/Hud/debugCommon.lua")
L0_0 = dofile
L0_0("/Debug/Hud/debugViewerParam.lua")
L0_0 = {}
function L0_0.cbLabelFontName(A0_1)
  local L2_2
  L2_2 = A0_1.cursor
  return string.format("%2d: size:%3d line_height:%2d: %s", A0_1[L2_2].font_no, A0_1[L2_2].font_size, A0_1[L2_2].line_height, A0_1[L2_2].font_name)
end
function L0_0.cbLabelColor(A0_3)
  if A0_3[4] ~= nil then
    return string.format("R:%3d B:%3d B:%3d A:%3d", A0_3[1].num, A0_3[2].num, A0_3[3].num, A0_3[4].num)
  end
  return string.format("R:%3d B:%3d B:%3d", A0_3[1].num, A0_3[2].num, A0_3[3].num)
end
function L0_0.getFontData(A0_4)
  local L3_5
  L3_5 = A0_4.cursor
  return A0_4[L3_5].font_no
end
function L0_0.getAlignData(A0_6)
  local L3_7
  L3_7 = A0_6.cursor
  return A0_6[L3_7].align
end
function L0_0.getBlendData(A0_8, A1_9)
  local L3_10, L4_11
  L3_10 = A0_8.cursor
  L4_11 = A0_8[L3_10]
  A1_9.srcColor = L4_11.srcColor
  A1_9.dstColor = L4_11.dstColor
  A1_9.srcAlpha = L4_11.srcAlpha
  A1_9.dstAlpha = L4_11.dstAlpha
end
L0_0.root = {
  {
    type = dbgCommon.kTypeTable,
    data_name = "text_id",
    data_label = "text_id",
    "ui_tuto_map_01",
    "ui_tuto_map_02",
    "ui_tuto_talisman_01",
    "ui_tuto_talisman_02",
    "ui_tuto_powerup_01",
    "ui_tuto_powerup_02",
    "ui_kagu_0_01",
    "ui_kagu_0_01",
    "ui_kagu_1_01",
    "ui_kagu_1_02",
    "ui_kagu_1_03",
    "ui_kagu_1_04",
    "ui_kagu_2_01",
    "ui_kagu_2_02",
    "ui_kagu_2_03",
    "ui_kagu_2_04",
    "ui_kagu_3_01",
    "ui_kagu_3_02",
    "ui_kagu_3_03",
    "ui_kagu_3_04",
    "ui_kagu_4_01",
    "ui_kagu_4_02",
    "ui_kagu_4_03",
    "ui_kagu_4_04",
    "ui_kagu_5_01",
    "ui_kagu_5_02",
    "ui_kagu_5_03",
    "ui_kagu_5_04",
    "ui_kagu_6_01",
    "ui_kagu_6_02",
    "ui_kagu_6_03",
    "ui_kagu_6_04",
    "ui_kagu_7_01",
    "ui_kagu_7_02",
    "ui_kagu_7_03",
    "ui_kagu_7_04",
    "ui_kagu_8_01",
    "ui_kagu_8_02",
    "ui_kagu_8_03",
    "ui_kagu_8_04",
    "ui_kagu_9_01",
    "ui_kagu_9_02",
    "ui_kagu_9_03",
    "ui_kagu_10_01",
    "ui_kagu_11_01",
    "ui_kagu_12_01",
    "ui_kagu_13_01",
    "ui_kagu_category_1",
    "ui_kagu_category_2",
    "ui_kagu_category_3",
    "ui_kagu_category_4",
    "ui_kagu_category_5",
    "ui_kagu_category_6",
    "ui_kagu_category_7",
    "ui_kagu_category_8",
    "ui_kagu_category_9",
    "ui_kagu_category_10",
    "ui_kagu_category_11",
    "ui_kagu_category_12",
    "ui_kagu_category_13",
    "ep90_00819",
    "ui_kaiwa_sp_line5",
    "ui_debug_pspose_01",
    "ui_debug_onlineid_1_1",
    "ui_debug_onlineid_1_2",
    "ui_debug_onlineid_2_1",
    "ui_debug_onlineid_2_2",
    "ui_debug_onlineid_3_1",
    "ui_debug_onlineid_3_2",
    "ui_newgame",
    "ui_debug_caption_01",
    "ui_debug_caption_02",
    "ui_debug_caption_03",
    "ui_debug_caption_04",
    "ui_debug_caption_05",
    "ui_debug_caption_06",
    "ui_debug_caption_07",
    "ui_debug_caption_08",
    "ui_debug_text_01",
    "ui_debug_text_02",
    "ui_debug_text_01_h",
    "ui_debug_text_02_h",
    "ui_debug_caption_09",
    "ui_debug_caption_10",
    "ui_debug_caption_11",
    "ui_debug_caption_12",
    "ui_debug_caption_13",
    "ui_debug_caption_14",
    "ui_debug_caption_15",
    "ui_debug_caption_16",
    "ui_debug_caption_17",
    "ui_debug_caption_18",
    "UI_test",
    "ui_caption_jimaku",
    "ui_caption_monologue",
    "ui_caption_tutorial",
    "ui_caption_jimaku_3",
    "ui_test_mojiretsu_1",
    "ui_ch_ghost_userid",
    "ui_loading_01",
    "ui_top_selects_01",
    "ui_top_selects_02",
    "ui_top_selects_03",
    "ui_top_selects_04",
    "ui_top_selects_05",
    "ui_top_selects_06",
    "ui_top_selects_07",
    "ui_top_header",
    "ui_acdialog_main_cm90",
    "ui_acdialog_main_cm91",
    "ui_acdialog_main_sm90",
    "ui_acdialog_main_sm91",
    "ui_acdialog_main_sm92",
    "ui_acdialog_main_sm93",
    "ui_acdialog_main_sm94",
    "ui_acdialog_main_ep90",
    "ui_acdialog_sub_01",
    "ui_acdialog_sub_02",
    "ui_acdialog_sub_03",
    "ui_acdialog_sub_04",
    "ui_acdialog_sub_05",
    "ui_object_ep90_01",
    "ui_object_fin_01",
    "ui_object_fin_02",
    "ui_option_01",
    "ui_option_02",
    "ui_option_03",
    "ui_option_04",
    "ui_option_05",
    "ui_option_06",
    "ui_option_07",
    "ui_option_system_01_01",
    "ui_option_system_01_02",
    "ui_option_system_02_01",
    "ui_option_header_01",
    "ui_option_header_02",
    "ui_option_header_03",
    "ui_option_reset_01",
    "ui_option_reset_02",
    "ui_option_01_02",
    "ui_option_02_02",
    "ui_option_02_01",
    "ui_option_01_01",
    "ui_topinfo_header_01",
    "ui_topinfo_button_01",
    "ui_topinfo_button_02",
    "ui_topinfo_main_ep90",
    "ui_topinfo_main_sm90",
    "ui_topinfo_main_sm91",
    "ui_topinfo_main_sm92",
    "ui_topinfo_main_sm93",
    "ui_topinfo_main_sm94",
    "ui_camera_guide_01",
    "ui_camera_guide_02",
    "ui_camera_guide_03",
    "ui_camera_guide_04",
    "ui_camera_guide_05",
    "ui_camera_guide_06",
    "ui_camera_guide_07",
    "ui_camera_guide_08",
    "ui_camera_guide_09",
    "ui_camera_guide_10",
    "ui_camera_guide_11",
    "ui_camera_guide_12",
    "ui_camera_guide_13",
    "ui_camera_guide_14",
    "ui_camera_guide_15",
    "ui_camera_guide_16",
    "ui_keyguide_info_01",
    "ui_keyguide_info_02",
    "ui_keyguide_info_03",
    "ui_keyguide_info_04",
    "ui_keyguide_cdemo_01",
    "ui_keyguide_cdemo_02",
    "ui_keyguide_ac_01",
    "ui_keyguide_ac_02",
    "ui_keyguide_ac_03",
    "ui_keyguide_tm_reslt_01",
    "ui_keyguide_tm_reslt_02",
    "ui_keyguide_tm_reslt_03",
    "ui_keyguide_tm_reslt_04",
    "ui_keyguide_cm_01",
    "ui_keyguide_cm_02",
    "ui_keyguide_cm_03",
    "ui_keyguide_cm_04",
    "ui_keyguide_menu_01",
    "ui_keyguide_system_01",
    "ui_keyguide_powerup_01",
    "ui_keyguide_film_01",
    "ui_keyguide_film_02",
    "ui_keyguide_fin_01",
    "ui_keyguide_map_01",
    "ui_keyguide_le_01",
    "ui_keyguide_le_02",
    "ui_keyguide_le_03",
    "ui_gameover_header",
    "ui_gameover_selects_01",
    "ui_gameover_selects_02",
    "ui_gameover_selects_03",
    "ui_gameover_selects_04",
    "ui_option_03_01",
    "ui_option_03_02",
    "ui_option_03_03",
    "ui_cdemo_ep_01",
    "ui_cdemo_ep_02",
    "ui_cdemo_ep_03",
    "ui_cdemo_ep_04",
    "ui_cdemo_ep_05",
    "ui_cdemo_ep_06",
    "ui_cdemo_ep_07",
    "ui_cdemo_ep_08",
    "ui_cdemo_ep_09",
    "ui_cdemo_ep_10",
    "ui_cdemo_ep_11",
    "ui_cdemo_ep_12",
    "ui_cdemo_ep_13",
    "ui_cdemo_ep_14",
    "ui_cdemo_ep_15",
    "ui_cdemo_ep_16",
    "ui_cdemo_ep_17",
    "ui_cdemo_ep_18",
    "ui_cdemo_ep_19",
    "ui_cdemo_ep_20",
    "ui_cdemo_ep_21",
    "ui_cdemo_ep_22",
    "ui_cdemo_ep_23",
    "ui_cdemo_ep_24",
    "ui_cdemo_ep_25",
    "ui_cdemo_ep_26",
    "ui_cdemo_ep_27",
    "ui_cdemo_title_01",
    "ui_cdemo_title_02",
    "ui_cdemo_title_03",
    "ui_cdemo_title_04",
    "ui_cdemo_title_05",
    "ui_cdemo_title_06",
    "ui_cdemo_title_07",
    "ui_cdemo_title_08",
    "ui_cdemo_title_09",
    "ui_cdemo_title_10",
    "ui_cdemo_title_11",
    "ui_cdemo_title_12",
    "ui_cdemo_title_13",
    "ui_cdemo_title_14",
    "ui_cdemo_title_15",
    "ui_cdemo_title_16",
    "ui_cdemo_title_17",
    "ui_cdemo_title_18",
    "ui_cdemo_title_19",
    "ui_cdemo_title_20",
    "ui_cdemo_title_21",
    "ui_cdemo_title_22",
    "ui_cdemo_title_23",
    "ui_cdemo_title_24",
    "ui_cdemo_title_25",
    "ui_cdemo_title_26",
    "ui_cdemo_title_27",
    "ui_option_04_01",
    "ui_option_04_02",
    "ui_option_04_03",
    "ui_sm_end_sm90",
    "ui_sm_main_sm90",
    "ui_sm_main_sm91",
    "ui_sm_main_sm92",
    "ui_sm_main_sm93",
    "ui_sm_main_sm94",
    "ui_sm_sub_sm90",
    "ui_sm_sub_01",
    "ui_sm_sub_02",
    "ui_sm_sub_03",
    "ui_sm_sub_04",
    "ui_sm_sub_05",
    "ui_hud_counter_slash_01",
    "ui_hud_counter_slash_02",
    "ui_ch_result_coin",
    "ui_tt_menu_selects_01",
    "ui_tt_menu_selects_02",
    "ui_tt_menu_selects_03",
    "ui_tt_menu_selects_04",
    "ui_tt_menu_selects_05",
    "ui_tt_menu_selects_06",
    "ui_tt_menu_selects_07",
    "ui_tt_menu_selects_08",
    "ui_tt_menu_caption_01",
    "ui_tt_menu_caption_02",
    "ui_tt_menu_caption_03",
    "ui_tt_menu_caption_04",
    "ui_hud_count_action",
    "ui_hud_count_courseout",
    "ui_hud_count_start",
    "ui_hud_count_01",
    "ui_hud_count_02",
    "ui_hud_count_03",
    "ui_hud_count_finish",
    "ui_tarisman_rt_header",
    "ui_tarisman_rt_alert",
    "ui_tarisman_rt_sub_01",
    "ui_tarisman_rt_sub_02",
    "ui_tarisman_rt_tag_01",
    "ui_tarisman_rt_tag_02",
    "ui_tarisman_rt_tag_03",
    "ui_tarisman_rt_tag_04",
    "ui_tarisman_rt_tag_05",
    "ui_tarisman_rt_tag_06",
    "ui_tarisman_rt_tag_07",
    "ui_tarisman_rt_tag_08",
    "ui_tarisman_rt_tag_09",
    "ui_tarisman_rt_cap_01",
    "ui_tarisman_rt_cap_02",
    "ui_tarisman_rt_cap_03",
    "ui_tarisman_rt_cap_04",
    "ui_tarisman_rt_cap_05",
    "ui_tarisman_rt_cap_06",
    "ui_tarisman_rt_cap_07",
    "ui_tarisman_rt_cap_08",
    "ui_tarisman_rt_cap_09",
    "ui_tarisman_1_01",
    "ui_tarisman_1_02",
    "ui_tarisman_2_01",
    "ui_tarisman_2_02",
    "ui_tarisman_3_01",
    "ui_tarisman_4_01",
    "ui_tarisman_4_02",
    "ui_tarisman_4_03",
    "ui_hud_counter_score_01",
    "ui_hud_counter_score_02",
    "ui_hud_counter_timer_01",
    "ui_ch_ghost_category_01",
    "ui_ch_ghost_category_02",
    "ui_ch_ghost_vs",
    "ui_challenge_selects_13",
    "ui_challenge_selects_14",
    "ui_challenge_selects_15",
    "ui_challenge_selects_16",
    "ui_challenge_header",
    "ui_challenge_hi_score",
    "ui_challenge_perfect",
    "ui_challenge_myscore",
    "ui_challenge_main1_00",
    "ui_challenge_main1_01",
    "ui_challenge_main1_cm90",
    "ui_challenge_main1_cm91",
    "ui_challenge_main2_00",
    "ui_challenge_main2_01",
    "ui_challenge_main2_cm90",
    "ui_challenge_main2_cm91",
    "ui_challenge_selects_01",
    "ui_challenge_selects_02",
    "ui_challenge_selects_03",
    "ui_challenge_selects_04",
    "ui_challenge_selects_05",
    "ui_challenge_selects_06",
    "ui_challenge_selects_07",
    "ui_challenge_selects_08",
    "ui_challenge_selects_09",
    "ui_challenge_selects_10",
    "ui_challenge_selects_11",
    "ui_challenge_selects_12",
    "ui_challenge_header_2",
    "ui_result_get_1",
    "ui_result_get_2",
    "ui_result_record_1",
    "ui_result_record_2",
    "ui_topinfo_object_01",
    "ui_top_caption_01",
    "ui_top_caption_02",
    "ui_top_caption_03",
    "ui_top_caption_04",
    "ui_top_caption_05",
    "ui_top_caption_06",
    "ui_top_caption_07",
    "ui_pause_header",
    "ui_pause_selects_01",
    "ui_pause_selects_02",
    "ui_pause_selects_03",
    "ui_pause_selects_04",
    "ui_pause_selects_05",
    "ui_pause_selects_06",
    "ui_pause_selects_07",
    "ui_pause_selects_08",
    "ui_map_navi_guide_01",
    "ui_map_navi_guide_02",
    "ui_map_navi_guide_03",
    "ui_map_msinfo_header_01",
    "ui_map_msinfo_header_02",
    "ui_map_msinfo_header_03",
    "ui_map_msinfo_header_04",
    "ui_map_msinfo_header_05",
    "ui_map_msinfo_guide_01",
    "ui_map_msinfo_main_01",
    "ui_map_msinfo_main_cm90",
    "ui_map_msinfo_main_cm91",
    "ui_map_msinfo_main_sm90",
    "ui_map_msinfo_main_sm91",
    "ui_map_msinfo_main_sm92",
    "ui_map_msinfo_main_sm93",
    "ui_map_msinfo_main_sm94",
    "ui_map_msinfo_main_ep90",
    "ui_map_header_hk_01",
    "ui_map_header_hk_02",
    "ui_map_header_hk_03",
    "ui_map_header_hk_04",
    "ui_map_header_bu_01",
    "ui_map_header_gp_01",
    "ui_map_header_gp_02",
    "ui_map_header_gp_03",
    "ui_map_header_gp_04",
    "ui_map_header_gp_05",
    "ui_map_header_gp_06",
    "ui_map_header_gp_07",
    "ui_map_header_ij_01",
    "ui_map_header_ij_02",
    "ui_map_header_ij_03",
    "ui_map_header_ot_01",
    "ui_map_header_ot_02",
    "ui_map_header_ot_03",
    "ui_map_header_ot_04",
    "ui_map_header_ot_05",
    "ui_map_header_ot_06",
    "ui_map_header_ot_07",
    "ui_map_header_sk_01",
    "ui_map_header_sk_02",
    "ui_map_header_sk_03",
    "ui_map_header_sk_04",
    "ui_map_header_sk_05",
    "ui_map_header_sk_06",
    "ui_map_header_sk_07",
    "ui_map_header_ms_001",
    "ui_map_header_ms_002",
    "ui_map_header_ms_003",
    "ui_map_header_ms_004",
    "ui_map_header_ms_005",
    "ui_map_header_ms_006",
    "ui_map_header_ms_007",
    "ui_map_header_ms_008",
    "ui_map_header_ms_009",
    "ui_map_header_ms_010",
    "ui_map_header_ms_011",
    "ui_map_header_ms_012",
    "ui_map_header_ms_013",
    "ui_map_header_ms_014",
    "ui_map_header_ms_015",
    "ui_map_header_ms_016",
    "ui_map_header_ms_017",
    "ui_map_header_ms_018",
    "ui_map_header_ms_019",
    "ui_map_header_ms_020",
    "ui_map_header_ms_021",
    "ui_map_header_ms_022",
    "ui_map_header_ms_023",
    "ui_map_header_ms_024",
    "ui_map_header_ms_025",
    "ui_map_header_ms_026",
    "ui_map_header_ms_027",
    "ui_map_header_ms_028",
    "ui_map_header_ms_029",
    "ui_map_header_ms_030",
    "ui_map_header_ms_031",
    "ui_map_header_ms_032",
    "ui_map_header_ms_033",
    "ui_map_header_ms_034",
    "ui_map_header_ms_035",
    "ui_map_header_ms_036",
    "ui_map_header_ms_037",
    "ui_map_header_ms_038",
    "ui_map_header_ms_039",
    "ui_map_header_ms_040",
    "ui_map_header_ms_041",
    "ui_map_header_ms_042",
    "ui_map_header_ms_043",
    "ui_map_header_ms_044",
    "ui_map_header_ms_045",
    "ui_map_header_ms_046",
    "ui_map_header_ms_047",
    "ui_map_header_ms_048",
    "ui_map_header_ms_049",
    "ui_map_header_ms_050",
    "ui_map_header_ms_051",
    "ui_map_header_ms_052",
    "ui_map_header_ms_053",
    "ui_map_header_ms_054",
    "ui_map_header_ms_055",
    "ui_map_header_ms_056",
    "ui_map_header_ms_057",
    "ui_map_header_ms_058",
    "ui_map_header_ms_059",
    "ui_map_header_ms_060",
    "ui_map_header_ms_061",
    "ui_map_header_ms_062",
    "ui_map_header_ms_063",
    "ui_map_header_ms_064",
    "ui_map_header_ms_065",
    "ui_map_header_ms_066",
    "ui_map_header_ms_067",
    "ui_map_header_ms_068",
    "ui_map_header_ms_069",
    "ui_map_header_ms_070",
    "ui_map_header_ms_071",
    "ui_map_header_ms_072",
    "ui_map_header_ms_073",
    "ui_map_header_ms_074",
    "ui_map_header_ms_075",
    "ui_map_header_ms_076",
    "ui_map_header_ms_077",
    "ui_map_header_ms_078",
    "ui_map_header_ms_079",
    "ui_map_header_ms_080",
    "ui_map_header_ms_081",
    "ui_map_header_ms_082",
    "ui_map_header_ms_083",
    "ui_map_header_ms_084",
    "ui_map_header_ms_085",
    "ui_map_header_ms_086",
    "ui_map_header_ms_087",
    "ui_map_header_ms_088",
    "ui_map_header_ms_089",
    "ui_map_header_ms_090",
    "ui_map_header_ms_091",
    "ui_map_header_ms_092",
    "ui_map_header_ms_093",
    "ui_map_header_ms_094",
    "ui_map_header_ms_095",
    "ui_map_header_ms_096",
    "ui_map_header_ms_097",
    "ui_map_header_ms_098",
    "ui_map_header_ms_099",
    "ui_map_header_ms_100",
    "ui_gaiku_01_01",
    "ui_gaiku_01_02",
    "ui_gaiku_01_03",
    "ui_gaiku_01_04",
    "ui_gaiku_01_11",
    "ui_gaiku_01_12",
    "ui_gaiku_01_13",
    "ui_gaiku_01_14",
    "ui_gaiku_01_15",
    "ui_gaiku_01_16",
    "ui_gaiku_01_17",
    "ui_gaiku_01_21",
    "ui_gaiku_01_31",
    "ui_gaiku_02_01",
    "ui_gaiku_02_02",
    "ui_gaiku_02_03",
    "ui_gaiku_02_04",
    "ui_gaiku_02_11",
    "ui_gaiku_02_12",
    "ui_gaiku_02_13",
    "ui_gaiku_02_14",
    "ui_gaiku_02_15",
    "ui_gaiku_02_16",
    "ui_gaiku_02_17",
    "ui_gaiku_02_21",
    "ui_gaiku_02_31",
    "ui_gaiku_03_01",
    "ui_gaiku_03_02",
    "ui_gaiku_03_03"
  },
  {
    type = dbgCommon.kTypeNode,
    data_label = "ViewParam",
    {
      type = dbgCommon.kTypeNode,
      data_label = "Pos",
      label = dbgCommon.cbLabelPos,
      {
        type = dbgCommon.kTypeInteger,
        data_name = "x",
        data_label = "X",
        step = 10,
        min = 0,
        max = 2000,
        num = 960
      },
      {
        type = dbgCommon.kTypeInteger,
        data_name = "y",
        data_label = "Y",
        step = 10,
        min = 0,
        max = 1000,
        num = 200
      }
    },
    {
      type = dbgCommon.kTypeNode,
      data_label = "bgColor",
      label = L0_0.cbLabelColor,
      {
        type = dbgCommon.kTypeInteger,
        data_name = "bg_r",
        data_label = "red",
        step = 16,
        min = 0,
        max = 255,
        num = 255
      },
      {
        type = dbgCommon.kTypeInteger,
        data_name = "bg_g",
        data_label = "green",
        step = 16,
        min = 0,
        max = 255,
        num = 255
      },
      {
        type = dbgCommon.kTypeInteger,
        data_name = "bg_b",
        data_label = "blue",
        step = 16,
        min = 0,
        max = 255,
        num = 255
      }
    },
    {
      type = dbgCommon.kTypeNode,
      data_label = "limitColor",
      label = L0_0.cbLabelColor,
      {
        type = dbgCommon.kTypeInteger,
        data_name = "limit_width_r",
        data_label = "red",
        step = 16,
        min = 0,
        max = 255,
        num = 48
      },
      {
        type = dbgCommon.kTypeInteger,
        data_name = "limit_width_g",
        data_label = "green",
        step = 16,
        min = 0,
        max = 255,
        num = 48
      },
      {
        type = dbgCommon.kTypeInteger,
        data_name = "limit_width_b",
        data_label = "blue",
        step = 16,
        min = 0,
        max = 255,
        num = 48
      }
    }
  },
  {
    type = dbgCommon.kTypeBoolean,
    data_name = "cc",
    data_label = "style",
    data = true
  },
  {
    type = dbgCommon.kTypeNode,
    data_label = "ConfigParam",
    {
      type = dbgCommon.kTypeTable,
      data_name = "font",
      data_label = "font",
      label = L0_0.cbLabelFontName,
      get_data = L0_0.getFontData,
      {
        font_no = 0,
        line_height = 0,
        font_size = 40,
        font_name = "MovieFont-TTF.ttf"
      },
      {
        font_no = 1,
        line_height = 0,
        font_size = 27,
        font_name = "MovieFont-TTF.ttf"
      },
      {
        font_no = 2,
        line_height = 0,
        font_size = 130,
        font_name = "G2UB_LINE.ttf"
      },
      {
        font_no = 3,
        line_height = 0,
        font_size = 26,
        font_name = "Gravity_Gaiji.ttf"
      },
      {
        font_no = 4,
        line_height = 0,
        font_size = 30,
        font_name = "MovieFont-TTF.ttf"
      },
      {
        font_no = 5,
        line_height = 0,
        font_size = 34,
        font_name = "MovieFont-TTF.ttf"
      },
      {
        font_no = 6,
        line_height = 0,
        font_size = 30,
        font_name = "Gravity_Gaiji.ttf"
      },
      {
        font_no = 7,
        line_height = 0,
        font_size = 45,
        font_name = "GillSansStd-UltraBoldCond.otf"
      },
      {
        font_no = 8,
        line_height = 0,
        font_size = 40,
        font_name = "GillSansStd-UltraBoldCond.otf"
      },
      {
        font_no = 9,
        line_height = 0,
        font_size = 42,
        font_name = "SCE-MaruFolkProH.otf"
      },
      {
        font_no = 10,
        line_height = 0,
        font_size = 80,
        font_name = "GillSansStd-UltraBold.otf"
      },
      {
        font_no = 11,
        line_height = 0,
        font_size = 40,
        font_name = "GillSansStd-UltraBold.otf"
      },
      {
        font_no = 12,
        line_height = 0,
        font_size = 45,
        font_name = "GillSansStd-Condensed.otf"
      },
      {
        font_no = 13,
        line_height = 0,
        font_size = 26,
        font_name = "MovieFont-TTF.ttf"
      },
      {
        font_no = 14,
        line_height = 0,
        font_size = 96,
        font_name = "GillSansStd-UltraBold.otf"
      },
      {
        font_no = 15,
        line_height = 0,
        font_size = 26,
        font_name = "SCE-MaruFolkProM.otf"
      },
      {
        font_no = 16,
        line_height = 0,
        font_size = 30,
        font_name = "SCE-MaruFolkProM.otf"
      },
      {
        font_no = 17,
        line_height = 0,
        font_size = 28,
        font_name = "SCE-MaruFolkProB.otf"
      },
      {
        font_no = 18,
        line_height = 0,
        font_size = 35,
        font_name = "SCE-MaruFolkProB.otf"
      },
      {
        font_no = 19,
        line_height = 0,
        font_size = 26,
        font_name = "SCE-MaruFolkProB.otf"
      },
      {
        font_no = 20,
        line_height = 0,
        font_size = 28,
        font_name = "SCE-MaruFolkProM.otf"
      },
      {
        font_no = 21,
        line_height = 0,
        font_size = 45,
        font_name = "SCE-MaruFolkProB.otf"
      },
      {
        font_no = 22,
        line_height = 0,
        font_size = 150,
        font_name = "G2UB_LINE.ttf"
      },
      {
        font_no = 23,
        line_height = 0,
        font_size = 30,
        font_name = "SCE-MaruFolkProM.otf"
      },
      {
        font_no = 24,
        line_height = 0,
        font_size = 30,
        font_name = "SCE-MaruFolkProB.otf"
      }
    },
    {
      type = dbgCommon.kTypeNode,
      data_label = "baseColor",
      label = L0_0.cbLabelColor,
      {
        type = dbgCommon.kTypeInteger,
        data_name = "r",
        data_label = "red",
        step = 16,
        min = 0,
        max = 255,
        num = 255
      },
      {
        type = dbgCommon.kTypeInteger,
        data_name = "g",
        data_label = "greed",
        step = 16,
        min = 0,
        max = 255,
        num = 255
      },
      {
        type = dbgCommon.kTypeInteger,
        data_name = "b",
        data_label = "blue",
        step = 16,
        min = 0,
        max = 255,
        num = 255
      },
      {
        type = dbgCommon.kTypeInteger,
        data_name = "a",
        data_label = "alpha",
        step = 16,
        min = 0,
        max = 255,
        num = 255
      }
    },
    {
      type = dbgCommon.kTypeNode,
      data_label = "frameColor",
      label = L0_0.cbLabelColor,
      {
        type = dbgCommon.kTypeInteger,
        data_name = "fr",
        data_label = "red",
        step = 16,
        min = 0,
        max = 255,
        num = 0
      },
      {
        type = dbgCommon.kTypeInteger,
        data_name = "fg",
        data_label = "green",
        step = 16,
        min = 0,
        max = 255,
        num = 0
      },
      {
        type = dbgCommon.kTypeInteger,
        data_name = "fb",
        data_label = "blue",
        step = 16,
        min = 0,
        max = 255,
        num = 0
      },
      {
        type = dbgCommon.kTypeInteger,
        data_name = "fa",
        data_label = "alpha",
        step = 16,
        min = 0,
        max = 255,
        num = 255
      }
    },
    {
      type = dbgCommon.kTypeNumber,
      data_name = "woffset",
      data_label = "woffset",
      step = 0.1,
      min = 0,
      max = 20,
      num = 0
    },
    {
      type = dbgCommon.kTypeNumber,
      data_name = "hoffset",
      data_label = "hoffset",
      step = 1,
      min = -40,
      max = 40,
      num = 0
    },
    {
      type = dbgCommon.kTypeNumber,
      data_name = "wscale",
      data_label = "wscale",
      step = 0.1,
      min = 0,
      max = 20,
      num = 1
    },
    {
      type = dbgCommon.kTypeNumber,
      data_name = "hscale",
      data_label = "hscale",
      step = 0.1,
      min = 0,
      max = 20,
      num = 1
    },
    {
      type = dbgCommon.kTypeNumber,
      data_name = "scale",
      data_label = "scale",
      step = 0.1,
      min = 0,
      max = 20,
      num = 1
    },
    {
      type = dbgCommon.kTypeNumber,
      data_name = "limit_width",
      data_label = "limit_width",
      step = 10,
      min = -1,
      max = 2000,
      num = -1
    },
    {
      type = dbgCommon.kTypeTable,
      data_name = "alignment",
      data_label = "alignment",
      get_data = L0_0.getAlignData,
      {align = -1, name = "default"},
      {align = 0, name = "left"},
      {align = 1, name = "center"},
      {align = 2, name = "right"},
      {
        align = 3,
        name = "left_limit_width"
      }
    },
    {
      type = dbgCommon.kTypeNumber,
      data_name = "fgap",
      data_label = "frame_width",
      step = 0.1,
      min = 0,
      max = 6,
      num = 1.2
    },
    {
      type = dbgCommon.kTypeBoolean,
      data_name = "is_bloom",
      data_label = "bloom",
      data = false
    }
  },
  {
    type = dbgCommon.kTypeTable,
    data_name = "blend",
    data_label = "blend",
    {
      name = "Alpha",
      srcColor = 2,
      dstColor = 6,
      srcAlpha = 1,
      dstAlpha = 2
    },
    {
      name = "Add",
      srcColor = 2,
      dstColor = 2,
      srcAlpha = 1,
      dstAlpha = 2
    },
    {
      name = "Mul",
      srcColor = 1,
      dstColor = 3,
      srcAlpha = 1,
      dstAlpha = 2
    },
    {
      name = "Invert",
      srcColor = 10,
      dstColor = 1,
      srcAlpha = 1,
      dstAlpha = 2
    },
    {
      name = "Screen",
      srcColor = 10,
      dstColor = 2,
      srcAlpha = 1,
      dstAlpha = 2
    },
    {
      name = "Xor",
      srcColor = 10,
      dstColor = 4,
      srcAlpha = 1,
      dstAlpha = 2
    },
    get_data_free_format = L0_0.getBlendData
  }
}
function L0_0.root.Execute(A0_12)
  HUD:testTextExit()
  wait(2)
  HUD:testTextCreate()
  TextParam = {}
  dbgCommon.get_param(TextParam, A0_12)
  Debug:setClearColor(true, TextParam.bg_r, TextParam.bg_g, TextParam.bg_b)
  HUD:testTextSetupText(TextParam)
end
function debugFont()
  Debug:setSwitch({"Display", "Debug Draw"}, true)
  Debug:setSwitch({
    "Display",
    "DebugDrawGroup",
    "Default"
  }, true)
  Debug:setSwitch({
    "Display",
    "File Asset Status"
  }, false)
  dbgCommon.TreeExecute(L0_0.root)
end
